---
dist: focal
language: python
python: "3.9"
sudo: required

services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:buster-slim
    - MOLECULE_DISTRO=debian:stretch-slim
    - MOLECULE_DISTRO=debian:jessie-slim
script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/