---

- name: REDIS_EXPORTER | Copy logrotate config
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/redis_exporter
    mode: 0644
    owner: root
    group: root
  when: redis_exporter_log_path is defined
