---

- name: REDIS_EXPORTER | Install
  ansible.builtin.include_tasks: install.yml
  tags:
    - install

- name: REDIS_EXPORTER | Configure
  ansible.builtin.include_tasks: config.yml
  tags:
    - configure

- name: REDIS_EXPORTER | Service
  ansible.builtin.include_tasks: service.yml
  tags:
    - service
