---

- name: REDIS_EXPORTER | Configuring service
  ansible.builtin.systemd:
    name: redis_exporter
    state: "{{ redis_exporter_service_state }}"
    enabled: "{{ redis_exporter_service_enabled }}"
    daemon_reload: yes
